"""Generate PCR by expiry for NIFTY and save to JSON file.

This script reuses `fetch_available_expiries` and `fetch_nifty_option_chain`
from `utils.py` and implements the same PCR computation logic as
`api_pcr_by_expiry` in `apps.py`.

Usage: run from repository root or ensure `Trading_dashboard_nse` is on PYTHONPATH.
python scripts/write_pcr_by_expiry.py
"""
import json
import os
from datetime import datetime

from utils import fetch_available_expiries, fetch_nifty_option_chain
from trend_storage import TrendStorage


def compute_pcr_for_expiry(exp):
    try:
        chain = fetch_nifty_option_chain(exp)
        records = chain.get('records', {})
        rows = records.get('data', [])
        spot_raw = records.get('underlyingValue') or records.get('underlying_value') or 0
        try:
            spot = float(str(spot_raw).replace(',', ''))
        except Exception:
            spot = 0

        # collect unique strikes
        strikes = sorted(list({ r.get('strikePrice') for r in rows if r.get('strikePrice') is not None }))

        # overall PCR (by OI)
        total_call_oi = 0
        total_put_oi = 0
        for r in rows:
            ce = r.get('CE', {}) or {}
            pe = r.get('PE', {}) or {}
            total_call_oi += ce.get('openInterest', 0) or 0
            total_put_oi += pe.get('openInterest', 0) or 0
        overall_pcr = round((total_put_oi / total_call_oi), 3) if total_call_oi else None

        # pcr over ±5 strikes from nearest to spot
        pcr_window = None
        if strikes and spot:
            nearest = min(strikes, key=lambda s: abs(s - spot))
            idx = strikes.index(nearest)
            low = max(0, idx - 5)
            high = min(len(strikes) - 1, idx + 5)
            selected = set(strikes[low:high+1])
            sel_call = 0
            sel_put = 0
            for r in rows:
                if r.get('strikePrice') in selected:
                    sel_call += (r.get('CE', {}) or {}).get('openInterest', 0) or 0
                    sel_put += (r.get('PE', {}) or {}).get('openInterest', 0) or 0
            pcr_window = round((sel_put / sel_call), 3) if sel_call else None

        return {
            'expiry': exp,
            'overall_pcr': overall_pcr,
            'pcr_plusminus_5': pcr_window,
            'spot': spot
        }
    except Exception as e:
        return {'expiry': exp, 'overall_pcr': None, 'pcr_plusminus_5': None, 'error': str(e)}


def main():
    out = []
    try:
        expiries = fetch_available_expiries('NIFTY')
    except Exception as e:
        print(f"Error fetching expiries: {e}")
        expiries = []

    if not expiries:
        print("No expiries found; exiting with empty output.")

    for exp in expiries:
        print(f"Processing expiry: {exp}")
        rec = compute_pcr_for_expiry(exp)
        out.append(rec)

    # ensure data directory
    data_dir = os.path.join(os.path.dirname(__file__), '..', 'data')
    data_dir = os.path.abspath(data_dir)
    os.makedirs(data_dir, exist_ok=True)

    filename = os.path.join(data_dir, 'pcr_by_expiry_nifty.json')
    meta = {
        'generated_at': datetime.utcnow().isoformat() + 'Z',
        'source': 'NSE option-chain via utils.fetch_nifty_option_chain'
    }
    payload = {'meta': meta, 'pcr_by_expiry': out}

    try:
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(payload, f, indent=2)
        print(f"Wrote PCR by expiry JSON to: {filename}")
    except Exception as e:
        print(f"Error writing output file: {e}")

    # Also write a snapshot into trend history (append)
    try:
        storage = TrendStorage()  # default trend_history.json
        # Try to pick a representative pcr_oi: use nearest expiry if available
        rep_pcr = None
        if out:
            # prefer the first entry that has overall_pcr
            for item in out:
                if item.get('overall_pcr') is not None:
                    rep_pcr = item.get('overall_pcr')
                    break

        trend_entry = {
            'timestamp': datetime.utcnow().isoformat(),
            'pcr_by_expiry': out,
            'pcr_oi': rep_pcr,
            'note': 'PCR by expiry snapshot generated by scripts/write_pcr_by_expiry.py'
        }
        storage.write_trend(trend_entry)
        print(f"Appended PCR snapshot to trend history: {storage.filepath}")
    except Exception as e:
        print(f"Error writing to trend history: {e}")


if __name__ == '__main__':
    main()
